<?php

namespace Database\Seeders;

use App\Models\SourceCategories;
use Illuminate\Database\Seeder;

class SourceCategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    private $newYorkTimesCategories = [
        ['name' => 'Adventure Sports'],
        ['name' => 'Arts & Leisure'],
        ['name' => 'Arts'],
        ['name' => 'Automobiles'],
        ['name' => 'Blogs'],
        ['name' => 'Books'],
        ['name' => 'Booming'],
        ['name' => 'Business Day'],
        ['name' => 'Business'],
        ['name' => 'Cars'],
        ['name' => 'Circuits'],
        ['name' => 'Classifieds'],
        ['name' => 'Connecticut'],
        ['name' => 'Crosswords & Games'],
        ['name' => 'Culture'],
        ['name' => 'DealBook'],
        ['name' => 'Dining'],
        ['name' => 'Editorial'],
        ['name' => 'Education'],
        ['name' => 'Energy'],
        ['name' => 'Entrepreneurs'],
        ['name' => 'Environment'],
        ['name' => 'Escapes'],
        ['name' => 'Fashion & Style'],
        ['name' => 'Fashion'],
        ['name' => 'Favorites'],
        ['name' => 'Financial'],
        ['name' => 'Flight'],
        ['name' => 'Food'],
        ['name' => 'Foreign'],
        ['name' => 'Generations'],
        ['name' => 'Giving'],
        ['name' => 'Global Home'],
        ['name' => 'Health & Fitness'],
        ['name' => 'Health'],
        ['name' => 'Home & Garden'],
        ['name' => 'Home'],
        ['name' => 'Jobs'],
        ['name' => 'Key'],
        ['name' => 'Letters'],
        ['name' => 'Long Island'],
        ['name' => 'Magazine'],
        ['name' => 'Market Place'],
        ['name' => 'Media'],
        ['name' => 'Men\'s Health'],
        ['name' => 'Metro'],
        ['name' => 'Metropolitan'],
        ['name' => 'Movies'],
        ['name' => 'Museums'],
        ['name' => 'National'],
        ['name' => 'Nesting'],
        ['name' => 'Obits'],
        ['name' => 'Obituaries'],
        ['name' => 'Obituary'],
        ['name' => 'OpEd'],
        ['name' => 'Opinion'],
        ['name' => 'Outlook'],
        ['name' => 'Personal Investing'],
        ['name' => 'Personal Tech'],
        ['name' => 'Play'],
        ['name' => 'Politics'],
        ['name' => 'Regionals'],
        ['name' => 'Retail'],
        ['name' => 'Retirement'],
        ['name' => 'Science'],
        ['name' => 'Small Business'],
        ['name' => 'Society'],
        ['name' => 'Sports'],
        ['name' => 'Style'],
        ['name' => 'Sunday Business'],
        ['name' => 'Sunday Review'],
        ['name' => 'Sunday Styles'],
        ['name' => 'T Magazine'],
        ['name' => 'T Style'],
        ['name' => 'Technology'],
        ['name' => 'Teens'],
        ['name' => 'Television'],
        ['name' => 'The Arts'],
        ['name' => 'The Business of Green'],
        ['name' => 'The City Desk'],
        ['name' => 'The City'],
        ['name' => 'The Marathon'],
        ['name' => 'The Millennium'],
        ['name' => 'The Natural World'],
        ['name' => 'The Upshot'],
        ['name' => 'The Weekend'],
        ['name' => 'The Year in Pictures'],
        ['name' => 'Theater'],
        ['name' => 'Then & Now'],
        ['name' => 'Thursday Styles'],
        ['name' => 'Times Topics'],
        ['name' => 'Travel'],
        ['name' => 'U.S.'],
        ['name' => 'Universal'],
        ['name' => 'Upshot'],
        ['name' => 'UrbanEye'],
        ['name' => 'Vacation'],
        ['name' => 'Washington'],
        ['name' => 'Wealth'],
        ['name' => 'Weather'],
        ['name' => 'Week in Review'],
        ['name' => 'Week'],
        ['name' => 'Weekend'],
        ['name' => 'Westchester'],
        ['name' => 'Wireless Living'],
        ['name' => 'Women\'s Health'],
        ['name' => 'Working'],
        ['name' => 'Workplace'],
        ['name' => 'World'],
        ['name' => 'Your Money'],
    ];

    private $guardianCategories = [
        [ "slug" => "about", "name" => "About" ],
        [ "slug" => "animals-farmed", "name" => "Animals farmed" ],
        [ "slug" => "artanddesign", "name" => "Art and design" ],
        [ "slug" => "australia-news", "name" => "Australia news" ],
        [ "slug" => "better-business", "name" => "Better Business" ],
        [ "slug" => "books", "name" => "Books" ],
        [ "slug" => "business", "name" => "Business" ],
        [ "slug" => "uk/business", "name" => "UK Business" ],
        [ "slug" => "us/business", "name" => "US Business" ],
        [ "slug" => "au/business", "name" => "AU Business" ],
        [ "slug" => "business-to-business", "name" => "Business to business" ],
        [ "slug" => "au/business-to-business", "name" => "AU Business to business" ],
        [ "slug" => "uk/business-to-business", "name" => "UK Business to business" ],
        [ "slug" => "us/business-to-business", "name" => "US Business to business" ],
        [ "slug" => "cardiff", "name" => "Cardiff" ],
        [ "slug" => "childrens-books-site", "name" => "Children's books" ],
        [ "slug" => "cities", "name" => "Cities" ],
        [ "slug" => "commentisree", "name" => "Opinion" ],
        [ "slug" => "au/commentisfree", "name" => "AU Opinion" ],
        [ "slug" => "uk/commentisfree", "name" => "UK Opinion" ],
        [ "slug" => "us/commentisfree", "name" => "US Opinion" ],
        [ "slug" => "community", "name" => "Community" ],
        [ "slug" => "crosswords", "name" => "Crosswords" ],
        [ "slug" => "culture", "name" => "Culture" ],
        [ "slug" => "au/culture", "name" => "AU Culture" ],
        [ "slug" => "uk/culture", "name" => "UK Culture" ],
        [ "slug" => "us/culture", "name" => "US Culture" ],
        [ "slug" => "culture-network", "name" => "Culture Network" ],
        [ "slug" => "culture-professionals-network", "name" => "Culture professionals network" ],
        [ "slug" => "edinburgh", "name" => "Edinburgh" ],
        [ "slug" => "education", "name" => "Education" ],
        [ "slug" => "enterprise-network", "name" => "Guardian Enterprise Network" ],
        [ "slug" => "environment", "name" => "Environment" ],
        [ "slug" => "au/environment", "name" => "AU Environment" ],
        [ "slug" => "uk/environment", "name" => "UK Environment" ],
        [ "slug" => "us/environment", "name" => "US Environment" ],
        [ "slug" => "extra", "name" => "Extra" ],
        [ "slug" => "fashion", "name" => "Fashion" ],
        [ "slug" => "film", "name" => "Film" ],
        [ "slug" => "au/film", "name" => "AU Film" ],
        [ "slug" => "uk/film", "name" => "UK Film" ],
        [ "slug" => "us/film", "name" => "US Film" ],
        [ "slug" => "food", "name" => "Food" ],
        [ "slug" => "football", "name" => "Football" ],
        [ "slug" => "games", "name" => "Games" ],
        [ "slug" => "global-development", "name" => "Global development" ],
        [ "slug" => "global-development-professionals-network", "name" => "Global Development Professionals Network" ],
        [ "slug" => "government-computing-network", "name" => "Guardian Government Computing" ],
        [ "slug" => "guardian-foundation", "name" => "Guardian Foundation" ],
        [ "slug" => "guardian-professional", "name" => "Guardian Professional" ],
        [ "slug" => "healthcare-network", "name" => "Healthcare Professionals Network" ],
        [ "slug" => "help", "name" => "Help" ],
        [ "slug" => "higher-education-network", "name" => "Higher Education Network" ],
        [ "slug" => "housing-network", "name" => "Housing Network" ],
        [ "slug" => "inequality", "name" => "Inequality" ],
        [ "slug" => "info", "name" => "Info" ],
        [ "slug" => "jobsadvice", "name" => "Jobs" ],
        [ "slug" => "katine", "name" => "Katine" ],
        [ "slug" => "law", "name" => "Law" ],
        [ "slug" => "leeds", "name" => "Leeds" ],
        [ "slug" => "lifeandstyle", "name" => "Life and style" ],
        [ "slug" => "au/lifeandstyle", "name" => "AU Life and style" ],
        [ "slug" => "uk/lifeandstyle", "name" => "UK Life and style" ],
        [ "slug" => "us/lifeandstyle", "name" => "US Life and style" ],
        [ "slug" => "local", "name" => "Local" ],
        [ "slug" => "local-government-network", "name" => "Local Leaders Network" ],
        [ "slug" => "media", "name" => "Media" ],
        [ "slug" => "au/media", "name" => "AU Media" ],
        [ "slug" => "uk/media", "name" => "UK Media" ],
        [ "slug" => "us/media", "name" => "US Media" ],
        [ "slug" => "media-network", "name" => "Media Network" ],
        [ "slug" => "membership", "name" => "Membership" ],
        [ "slug" => "money", "name" => "Money" ],
        [ "slug" => "uk/money", "name" => "AU Money" ],
        [ "slug" => "us/money", "name" => "UK Money" ],
        [ "slug" => "au/money", "name" => "US Money" ],
        [ "slug" => "music", "name" => "Music" ],
        [ "slug" => "news", "name" => "News" ],
        [ "slug" => "politics", "name" => "Politics" ],
        [ "slug" => "public-leaders-network", "name" => "Public Leaders Network" ],
        [ "slug" => "science", "name" => "Science" ],
        [ "slug" => "search", "name" => "Search" ],
        [ "slug" => "small-business-network", "name" => "Guardian Small Business Network" ],
        [ "slug" => "social-care-network", "name" => "Social Care Network" ],
        [ "slug" => "social-enterprise-network", "name" => "Social Enterprise Network" ],
        [ "slug" => "society", "name" => "Society" ],
        [ "slug" => "society-professionals", "name" => "Society Professionals" ],
        [ "slug" => "sport", "name" => "Sport" ],
        [ "slug" => "uk/sport", "name" => "AU Sport" ],
        [ "slug" => "us/sport", "name" => "UK Sport" ],
        [ "slug" => "au/sport", "name" => "US Sport" ],
        [ "slug" => "stage", "name" => "Stage" ],
        [ "slug" => "teacher-network", "name" => "Teacher Network" ],
        [ "slug" => "technology", "name" => "Technology" ],
        [ "slug" => "au/technology", "name" => "AU Technology" ],
        [ "slug" => "uk/technology", "name" => "UK Technology" ],
        [ "slug" => "us/technology", "name" => "US Technology" ],
        [ "slug" => "theguardian", "name" => "From the Guardian" ],
        [ "slug" => "theobserver", "name" => "From the Observer" ],
        [ "slug" => "travel", "name" => "Travel" ],
        [ "slug" => "au/travel", "name" => "AU Travel" ],
        [ "slug" => "uk/travel", "name" => "UK Travel" ],
        [ "slug" => "us/travel", "name" => "US Travel" ],
        [ "slug" => "travel/offers", "name" => "Guardian holiday offers" ],
        [ "slug" => "tv-and-radio", "name" => "Television & radio" ],
        [ "slug" => "uk-news", "name" => "UK news" ],
        [ "slug" => "us-news", "name" => "US news" ],
        [ "slug" => "voluntary-sector-network", "name" => "Voluntary Sector Network" ],
        [ "slug" => "weather", "name" => "Weather" ],
        [ "slug" => "women-in-leadership", "name" => "Women in Leadership" ],
        [ "slug" => "working-in-development", "name" => "Working in development" ],
        [ "slug" => "world", "name" => "World news" ]
    ];
    public function run(): void
    {
        $mappedNewYorkTimesCategories = array_map(function ($category) {
            return array_merge($category, ['source_id' => 2], ['slug' => $category['name']]);
        }, $this->newYorkTimesCategories);
        // $newYorkTimesCategoriesMerged = array_merge($mappedNewYorkTimesCategories);
        foreach ($mappedNewYorkTimesCategories as $category) {
            SourceCategories::create($category);
        }

        $mappedGuardianCategories = array_map(function ($category) {
            return array_merge($category, ['source_id' => 1]);
        }, $this->guardianCategories);

        foreach ($mappedGuardianCategories as $category) {
            SourceCategories::create($category);
        }
    }
}